<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.venkuuz.bookstore</groupId>
    <artifactId>bookstore-ms-app</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>book-store-webapp</name>
    <properties>
        <java.version>21</java.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <modules>
        <module>catalog-service/catalog-service</module>
        <module>order-service/order-service</module>
    </modules>
    <build>
        <plugins>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>2.43.0</version>
                <configuration>
                    <!--<java>
                        <importOrder/>
                        <removeUnusedImports/>
                        <googleJavaFormat>
                            <version>1.21.0
                            </version>                      &lt;!&ndash; optional, 1.8 is the minimum supported version for Java 11 &ndash;&gt;
                            <style>GOOGLE</style>                       &lt;!&ndash; or AOSP (optional) &ndash;&gt;
                            <reflowLongStrings>true</reflowLongStrings> &lt;!&ndash; optional &ndash;&gt;
                            <formatJavadoc>false</formatJavadoc>        &lt;!&ndash; optional &ndash;&gt;
                            &lt;!&ndash; optional: custom group artifact (you probably don't need this) &ndash;&gt;
                            <groupArtifact>com.google.googlejavaformat:google-java-format</groupArtifact>
                        </googleJavaFormat>
                    </java>-->
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>